### ISSUE TITLE
why tho

### ISSUE THREAD

**Issue by jman1593** [v4for/v4for.github.io#3]
Bro, why did u report strongdog at summit? Its suck a jerk move, especially from you.

**Comment by phexus23** [comment]
bro what did i do

**Comment by phexus23** [comment]
oh josh btw, if you take like some of the games i have to reverse engineer, could you credit me and the website? it's a lot of work for some games(like smashkarts)

**Comment by jman1593** [comment]
i wasnt taking the games, i was just very annoyed u reported it at summit accademy. also, if i take games, i will credit you.

**Comment by jman1593** [comment]
ok, actually, i am very impressed you got smashcarts, i will credit you. still tho.

**Comment by jman1593** [comment]
wait, how did u remove the sitelock tho? ive tried to do that and it never works

**Comment by phexus23** [comment]
ok numero uno, i didn't report you to summit academy that's not very nice and pretty scummy, numbers dous i think your confusing me with max w, i'm maxwell s btw, i think you know me.

**Comment by phexus23** [comment]
oh and abt SK if it's open in an iframe it auto blocks it so that's nice, if you really really want to you could probably read the pokisdk.js files. 

(they are required don't forget them)
also, pixel gun apocalypse and pixel speed run source code is here, i noticed on your site that they are blocked because they are embedding construct. gl 👍

**Comment by phexus23** [comment]
oh smth in forgot it's in the sss folder

**Comment by jman1593** [comment]
ik for the sss, I am not confusing u for max (ik ur rextons older brother) but i got info from some people that said u did report it, and thanks for alearting me about the blocked games.

**Comment by phexus23** [comment]
oh no i didnt report your site, i think some peope just think that because people are using my site now that yours is blocked.

**Comment by jman1593** [comment]
no, rexton said u did

**Comment by phexus23** [comment]
let me talk to that kid, i swear ong i didn't report it.

**Comment by jman1593** [comment]
he told it to austin wild and austin told it to me (I haven't talked to Rexton for like a year now)

**Comment by phexus23** [comment]
ok yeah, but i don’t understand, i didn’t report

**Comment by phexus23** [comment]
how can i proved that

**Comment by phexus23** [comment]
i can’t help you unblock it or anything so what do you want me to do??

**Comment by jman1593** [comment]
no, i can unblock it, i was just wondering why u did, but ill belive u didn't. sorry for bothering you, I was just curios (i guess it is a rumor going around there)

**Comment by jman1593** [comment]
sorry again!

**Comment by MaxWeichers** [comment]
YOU TOOK STRONGDOG FROM ME, anyway I do not care enough anymore

Sent with [Proton Mail](https://proton.me/) secure email.

**Comment by jman1593** [comment]
bud, I never took it from u, the domain was always mine, and i re-coded it so you can't be saying CRAP about me taking it from you. If you want it so bad, go make a new site with a whole new domain, and just title in general.

**Comment by jman1593** [comment]
also, if u don't care, why do u keep bothering me about it?
